version: '3.3'
services:
  caddy:
    image: caddy:latest
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 8080:8080
    networks:
      - proxy
    depends_on:
      - frontend
      - backend
  frontend:
    build: ./frontend
    networks:
      - proxy
  backend:
    build: ./backend
    env_file: .env
    networks:
      - proxy
networks:
  proxy:
